spring.application.name=FinanceProject
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url= jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=root
spring.datasource.password=Arjun#123
spring.jpa.show-sql=true
server.port=8081
jwt.secretKey = QWxpY2VTZWNyZXRLZXlYWFhYWFhYWFhYWFhYWFhYWFg=
jwt.expirationTime=3600000